CREATE TABLE users (
	user_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(256) NOT NULL,
	age VARCHAR(256) NOT NULL,
	email VARCHAR(256) NOT NULL,
    hash_password VARCHAR(256) NOT NULL,
    is_active tinyint DEFAULT 0,
    role INT(2) DEFAULT 0,
	created_at DATETIME  DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME 
);
CREATE TABLE roles (
	role_id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(256) NOT NULL
);
CREATE TABLE posts (
	post_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(256) NOT NULL,
	content text NOT NULL,
	image_string VARCHAR(256),
    likes INT DEFAULT 0,
	created_at DATETIME  DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME 
);
